GET http://localhost:8080/spring-mvc-app/api/v1/user/all

###

GET http://localhost:8080/spring-mvc-app/api/v1/user/11


###

POST http://localhost:8080/spring-mvc-app/api/v1/user
Content-Type: application/json

{
  "username": "Vash",
  "password": "Vash",
  "email": "Vash@mail.cc",
  "age": 30
}

###

PUT http://localhost:8080/spring-mvc-app/api/v1/user
Content-Type: application/json

{
  "id": 11,
  "username": "Vash1",
  "password": "Vash",
  "email": "Vash@mail.cc",
  "age": 30
}

###
DELETE http://localhost:8080/spring-mvc-app/api/v1/user/11